all : opt

# lsb : arch_final_lsb.cpp
# 	g++ arch_final_lsb.cpp -o arch_final_lsb
lsb : arch_final_lsb.cpp
	g++ -g -std=c++11 arch_final_lsb.cpp -o project
opt : arch_final_opt.cpp
	g++ -g -std=c++11 arch_final_opt.cpp -o project